/*
  Copyrights reserved
  Written by Paul Hwang
  File name: session_mgr_protocol.h
*/

#pragma once

#define SESSION_MGR_DATA_BUFFER_SIZE 512

#define SESSION_MGR_PROTOCOL_SESSION_ID_SIZE 4
#define SESSION_MGR_PROTOCOL_SESSION_INDEX_SIZE 4
#define SESSION_MGR_PROTOCOL_SESSION_ID_INDEX_SIZE (SESSION_MGR_PROTOCOL_SESSION_ID_SIZE + SESSION_MGR_PROTOCOL_SESSION_INDEX_SIZE)
